# Generated by Django 4.2.30 on 2026-09-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do Tweet')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True, verbose_name='Palavra-chave')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('text', models.TextField(verbose_name='Texto do Tweet')),
                ('target', models.IntegerField(verbose_name='Alvo (0=Não, 1=Sim)')),
            ],
            options={
                'verbose_name': 'Tweet de Desastre',
                'verbose_name_plural': 'Tweets de Desastres',
                'db_table': 'disaster_tweets',
                'ordering': ['id'],
            },
        ),
    ]
